version: '2.1'
services:
  mysql:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW:-root}"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "${DB_USER:-test}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-test}"
      TZ: "Europe/Berlin"

  # TODO: add solr

  php:
    image: ghcr.io/elbformat/ibexa-behat-bundle/php
    environment:
      DATABASE_URL: 'mysql://test:test@mysql:3306/test'

    depends_on:
      - mysql
    volumes:
      - ./:/var/www
